### PR TITLE
Fix frame_count cli option logic when using skip

### PR DESCRIPTION
**Pull request by BoatsMcGee**
With the recent refactor, the `skip` feature no longer affects the `decode_count` value. This means the decode_count starts at 0 *after* skipping and we no longer need to subtract the `skip` value from the `decode_count` value before checking if the frames quota has been reached. This PR also simplifies the argument by making it shorter as suggested by @Gui-Yom in PR #7. Should there be a naming conflict in the future we can cross that bridge when we get there.

Thank you,
\- Boats

### CODE REVIEW

**Comment by Gui-Yom** [comment]
I think I fixed it with https://github.com/Gui-Yom/turbo-metrics/commit/1a787e011a16e07527828f22319ee4fb9064f1ac

**Comment by BoatsMcGee** [comment]
Ah, what timing! I'll merge in the upstream changes and see what can be done from there.

Thanks,
\- Boats

**Comment by Gui-Yom** [comment]
`compute_all` fixed in https://github.com/Gui-Yom/turbo-metrics/commit/e89d76bff8d08020916db0dda94cfab1638929af

**Comment by BoatsMcGee** [comment]
Confirmed the output is just as expected with combinations of `skip` and `frames`. Great work! I'll go ahead and close this PR as resolved.

Thank you,
\- Boats

**Pull request closed without merging**
